### ISSUE TITLE
Problemer med anaconda environment efter installation

### ISSUE THREAD

**Issue by Mthornit** [dtudk/dtumathtools#1]
Hej, vi er en gruppe på tre, der alle har fået problemer med Spyder i vores Anaconda Environment efter installation af DTUMathTools i går. Vi kan starte Anaconda, og Jupyter Notebooks kører stadigvæk.

**Comment by Chrillebon** [comment]
Kan du komme med nogle eksempler på hvad der ikke virker, eller hvilken fejlbesked du får?

**Comment by Mthornit** [comment]
Den skrev bare at der var problemer med at starte Spyder. Og da jeg så opdaterede Anaconda blev det til "could not find or load the Qt platform plugin" når jeg startede Anaconda.

**Comment by Chrillebon** [comment]
Ikke noget jeg er stødt på selv, men lyder som en konflikt mellem anaconda og pakken "PyQt5", baseret på 
https://stackoverflow.com/questions/41994485/how-to-fix-could-not-find-or-load-the-qt-platform-plugin-windows-while-using-m

Den mest simple forslag til en løsning, som jeg ville prøve først (også fra dette link) er at køre følgende linjer fra en Anaconda terminal:

  conda remove qt
  conda remove pyqt 
  conda install qt 
  conda install pyqt

**Comment by Mthornit** [comment]
Det virker desværre ikke. Så kan selve Anaconda heller ikke åbne. Må bare begynde at bruge Pycharm i stedet for Spyder

**Comment by Chrillebon** [comment]
Since qt is no longer a strict requirement for installing the package, I am closing this issue.
