### ISSUE TITLE
add conda forge feedstock

### ISSUE THREAD

**Issue by zerothi** [dtudk/dtumathtools#20]

**Comment by zerothi** [comment]
@Chrillebon I will list you as author for the dtumathtools feedstock for conda. Then we are at least two persons!

Hope you don't mind, but it is vital for the conda-forge community that you agree!

**Comment by Chrillebon** [comment]
Sounds great! Let me know if any further action is needed from my side before the package can be added to conda.

**Comment by zerothi** [comment]
Everything should be fine, you shouldn't be required to do anything. :)
I'll let you know if anything is required.

**Comment by zerothi** [comment]
Completed.

**Comment by zerothi** [comment]
Find the feedstock [here](https://github.com/conda-forge/dtumathtools-feedstock)
