### ISSUE TITLE
Version tag

### ISSUE THREAD

**Issue by zerothi** [dtudk/dtumathtools#28]
Hi @Chrillebon 

How have you created the pypi release? There is no tags (remember it should be annotatted), and no branches?

Yet, you have released 2024.1.0?

Could you please tell me what you did?

**Comment by Chrillebon** [comment]
After the final PR, I pulled all changes locally, then [built and uploaded](https://packaging.python.org/en/latest/tutorials/packaging-projects/) to PyPi. I have not taken any further action.
Sorry if I have missed a step before pushing to PyPi.

**Comment by Chrillebon** [comment]
Let me know if I need to change anything wrt. PyPi/upload.

**Comment by zerothi** [comment]
Nothing we can do now, it would require a new version. Lets see if this will work fine.

**Comment by Chrillebon** [comment]
I still have the option to [yank](https://peps.python.org/pep-0592/)(or worst case delete) this version if we do not want this version number out. But let me know what you want.

**Comment by zerothi** [comment]
Let's keep it, I think if you delete it, we can't upload new versions. If anything we'll do a 2024.1.1 release, but not an issue now :)
