### ISSUE TITLE
Moving to dtudk organization

### ISSUE THREAD

**Issue by zerothi** [dtudk/dtumathtools#9]
Hi!

I am Nick from DCC (@ DTU), and we are governing the https://github.com/dtudk/ namespace.

Your project will be used by *all* students as they join the DTU introductory courses (math or programming or...).
As such we believe it is important that students has confidence in a package affiliation with the teaching environment they exist in. 
At least at the "top level". 

I have discussed with Tue and Jakob about moving your repository to the dtudk namespace for consistency.
This will have limited impact.
- the project will be hosted on github.com/dtudk/dtumathtools
- you will still get access to it as maintainers and should thus be able to do everything you do now.
- External collaborators would need approval (from dtudk admins)
- external contributions via forks are not impacted.

As such we do not plan to impact, or steal, your work. Only to ensure that students will see the DTU affiliation directly.

If you have any questions, feel free to let me know!

**Comment by Chrillebon** [comment]
I completely agree. The current model works as long as I am a part of the team ;)
You should then also create a pypi account, so the dtudk team can push new packages. dm me when this is done

**Comment by zerothi** [comment]
The plan is not to expell any current members of the team, if you feel all are necessary.
This is primarily (only) about its location.
If you are the responsible, you will still be the responsible, and hence there shouldn't be any others who can publish to pypi etc.

It would, however, be ideal if you could invite me (username: zeroth) as maintainer/owner. Then both you and me can publish the package. Do note, that I intent to **NOT** do anything without your consent. I plan to stay in the background and aid only IFF this is required by you or any teacher, as such there shouldn't be any problems related to the pypi upload stuff.

I believe this can be controlled on the pypi site, `manage/project/dtumathtools/settings/publishing` where one can specify namespace, and package name.

I would then recommend you propose a transfer to the dtudk namespace (and await for my approval).
I'll create a new team on the namespace with all current developers of dtumathtools.

Let me propose that the project name will be all lowercase: "dtumathtools", so it reflects the package name for `pip`, I believe you can do this when transferring.

Let me know what you think?

**Comment by zerothi** [comment]
I have invited you to a team, once it has been moved, I need to assign the team as maintainers, and then nothing more should be required, access are as they were etc.

**Comment by Chrillebon** [comment]
As I "_don’t have the permission to create public repositories on dtudk_", I am unable to do the transfer to dtudk currently. I will do it as soon as I am able to.

For the transfer of the pypi project to dtudk, the organization need to be created first. Do you want to create (and thus be owner of) that?

**Comment by zerothi** [comment]
> As I "_don’t have the permission to create public repositories on dtudk_", I am unable to do the transfer to dtudk currently. I will do it as soon as I am able to.
> 
> For the transfer of the pypi project to dtudk, the organization need to be created first. Do you want to create (and thus be owner of) that?

dtudk is already created, so you should be able to do so as soon as you have accepted the `dtumathtools` invite from dtudk (you should have gotten one?)

**Comment by zerothi** [comment]
Ah, saw you have accepted, so I think it should be ready now?

**Comment by Chrillebon** [comment]
Do not think that fixed it... Now it simply claims that "dtudk/dtumathtools already exists and You don’t have the permission to create public repositories on dtudk".

**Comment by zerothi** [comment]
Hmm.. I have just checked, it won't work until you are admin in that org, the easiest would be to jest transfer it to me, then I can move it. I have admin rights there.
I'll fix everything tomorrow, if this is ok?

To be on the safe side, you can just have a local copy, I will also have one.

**Comment by zerothi** [comment]
@Chrillebon a gentle ping, do you mind trying to move it to me? zerothi? I'll move it again... That seems like the simplest path.

**Comment by zerothi** [comment]
@Chrillebon thanks! Now done! You should still have access, let me know if there are problems.
I have invited the other two contributors as team members to maintain the package, so far no response.
If anybody needs access, let me know! :)

Thanks!
